#!/bin/bash
	BLACK="$HOME/code/gogo/gogo -gtp -go -stats -gfx -t 10 -c 0.5 -k 1000 -log gogo.log -amaf -neighbors -ancestor -seed -cutoff 0.5 -v"
if [[ !(-z $1) ]]; then
	BLACK="$BLACK -pat -tenuki -pfile $1"
fi
WHITE="$HOME/code/gnugo-3.8/interface/gnugo --mode gtp --capture-all-dead --chinese-rules --never-resign --level 10"
gogui-twogtp \
	-black "gogui-display \"$BLACK\"" \
	-white "$WHITE" \
	-games 1 -size 9 -sgffile gnugo_gfx -auto -komi 6.5
