#!/bin/bash
if [[ -z $1 ]]; then
	BLACK="$HOME/code/gogo/gogo -gtp -go -stats -gfx -t 10 -c 0.5 -e 2 -k 1000 -log gogo.log -amaf -neighbors -seed"
else 
	BLACK="$HOME/code/gogo/gogo -gtp -go -stats -gfx -t 10 -e 10 -log gogo.log -amaf -eval -efile $1 -k 100"
fi
WHITE="$HOME/code/gnugo-3.8/interface/gnugo --mode gtp --capture-all-dead --chinese-rules --never-resign --level 10"
gogui-twogtp \
	-black "gogui-display \"$BLACK\"" \
	-white "$WHITE" \
	-games 1 -size 9 -sgffile gnugo_gfx -auto -komi 6.5
