#!/bin/sh
./make
GOGO="./gogo -gtp -p=50000 -stats -gfx -uct -c=0.2 -k=10000 -e=50"
gogui-twogtp \
	-black "gogui-display \"$GOGO\"" \
	-white "gogui-display \"$GOGO\"" \
	-games 100 -size 9 -sgffile GoGoTest10000 -auto
