#!/bin/bash
SIX="/home/jpettit/code/six-0.5.3/six/gtp beginner"
GOGO="/home/jpettit/code/gogo/gogo -gtp -uct -c=0.5 -k=1000 -p=100000 -stats -hex -tablepat -file /home/jpettit/code/gogo/analysis/swarm-1-1.gob -config disabled.json"
function play {
	BLACK=$GOGO
	WHITE=$SIX
	gogui-twogtp -auto -size 10 -black "$BLACK" -white "$WHITE" -games 1 -sgffile disabled_$1 -verbose
}
play reduced
