#!/bin/bash
MOHEX="$HOME/code/benzene-0.9.0/src/mohex/mohex"
GOGO="$HOME/code/gogo/gogo -gtp -uct -k=1000 -t=5 -hex -tablepat -file $1"
function play {
	BLACK=$GOGO
	WHITE=$MOHEX
	gogui-twogtp -auto -size 13 -black "$BLACK" -white "$WHITE" \
		-games 500 -sgffile mohex -verbose -alternate -openings openings13
}
play
