#!/bin/bash
MOHEX="/home/jpettit/Downloads/benzene-0.9.0/src/mohex/mohex"
GOGO="/home/jpettit/code/gogo/gogo -gtp -uct -k=10000 -t=10 -stats -hex -tablepat -file /home/jpettit/code/gogo/testing/new-swarms/swarm-64.gob"
function play {
	BLACK=$GOGO
	WHITE=$MOHEX
	gogui-twogtp -auto -size 13 -black "$BLACK" -white "$WHITE" \
		-games 500 -sgffile mohex -verbose -alternate -openings openings13
}
play
