#!/bin/bash
SIX="$HOME/code/six-0.5.3/six/gtp expert"
GOGO="$HOME/code/gogo/gogo -gtp -uct -k=1000 -t=5 -hex -tablepat -file $1"
function play {
	BLACK=$GOGO
	WHITE=$SIX
	gogui-twogtp -auto -size 11 -black "$BLACK" -white "$WHITE" -games 1 -sgffile six -verbose -openings openings11 -alternate
}
play
