#!/bin/sh
gogui-twogtp -auto -size 11 \
	-white \
	"/home/jpettit/code/gogo/gogo -gtp -p=100000 -k=1000 -uct -hex" \
	-black \
	"/home/jpettit/code/gogo/gogo -gtp -p=100000 -k=1000 -uct -hex" \
	-verbose -games 100 -sgffile selfplay -openings openings 2>err
