#!/bin/sh
gogui-twogtp -auto -size 13 \
	-black \
	"$HOME/code/gogo/gogo -gtp -t 5 -k 1000 -uct -hex -tablepat -file $1" \
	-white \
	"$HOME/code/gogo/gogo -gtp -t 5 -k 1000 -uct -hex" \
	-verbose -games 100 -sgffile selfplay -openings openings13 -alternate
