include $(GOROOT)/src/Make.inc

TARG=gogo
GOFILES=\
asgtypes.go\
config.go\
gtp.go\
learning.go\
search.go\
tracker.go\
zobrist.go\
board_eval.go\
dfs.go\
gotracker.go\
hextracker.go\
sgf.go\
weight_tree.go\
cluster.go\
main.go

include $(GOROOT)/src/Make.cmd
